# 每一个键值对必须填写
gin:
  mode: "debug"
# Server configuration
server:
  addr: "127.0.0.1:8080"           # 监听地址, default ":8700"
  read_timeout: 10        # 读取超时时长
  write_timeout: 10       # 写入超时时长
  max_header_bytes: 20    # 最大的header大小，二进制位长度
  allow_ip:
    - "127.0.0.1"
    - "192.168.1.1"

# Log configuration
log:
  level : "debug"
  filename: "logs/gateway.log"
  error_filename: "logs/gateway_error.log"
  max_size: 50
  max_backups: 10
  max_age: 7
  compress: false
 

# MySQL configuration
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Dan10130204#@"
  dbname: "api_gateway"
  charset: "utf8mb4"
  parsetime: true
  maxidleconns: 100
  maxopenconns: 100

# Redis configuration
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  poolsize: 10
  minidleconns: 2
  dialtimeout: "5s"
  readtimeout: "5s"
  writetimeout: "5s"

# Swagger configuration
swagger:
  version: "1.0.0"
  host: "localhost:8080"
  base_path: "/api/v1"
  schemes:
    - "http"
    - "https"
  title: "Gateway API "
  description: ""
